CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "otps" ("id" integer primary key autoincrement not null, "identifier" varchar not null, "token" varchar not null, "validity" integer not null, "valid" tinyint(1) not null default '1', "created_at" datetime, "updated_at" datetime);
CREATE INDEX "otps_id_index" on "otps" ("id");
CREATE TABLE IF NOT EXISTS "media" ("id" integer primary key autoincrement not null, "model_type" varchar not null, "model_id" integer not null, "uuid" varchar, "collection_name" varchar not null, "name" varchar not null, "file_name" varchar not null, "mime_type" varchar, "disk" varchar not null, "conversions_disk" varchar, "size" integer not null, "manipulations" text not null, "custom_properties" text not null, "generated_conversions" text not null, "responsive_images" text not null, "order_column" integer, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "media_model_type_model_id_index" on "media" ("model_type", "model_id");
CREATE UNIQUE INDEX "media_uuid_unique" on "media" ("uuid");
CREATE INDEX "media_order_column_index" on "media" ("order_column");
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "parent_id" integer, "slug" varchar not null, "name" varchar not null, "created_at" datetime, "updated_at" datetime, foreign key("parent_id") references "categories"("id") on delete set null);
CREATE UNIQUE INDEX "categories_slug_unique" on "categories" ("slug");
CREATE TABLE IF NOT EXISTS "members" ("id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "phone" varchar not null, "gender" varchar not null, "dob" date, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "members_email_unique" on "members" ("email");
CREATE UNIQUE INDEX "members_phone_unique" on "members" ("phone");
CREATE TABLE IF NOT EXISTS "pages" ("id" integer primary key autoincrement not null, "name" varchar not null, "contents" text not null, "published" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "FAQs" ("id" integer primary key autoincrement not null, "question" varchar not null, "answer" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "contact_us" ("id" integer primary key autoincrement not null, "member_id" integer, "first_name" varchar not null, "last_name" varchar not null, "email" varchar not null, "phone" varchar not null, "reason" text not null, "created_at" datetime, "updated_at" datetime, foreign key("member_id") references "members"("id") on delete set null);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "bookings" ("id" integer primary key autoincrement not null, "member_id" integer, "category_id" integer, "sub_category_id" integer, "booking_id" integer not null, "request_status" varchar not null, "payment_status" varchar not null, "lat" float, "lng" float, "address" varchar, "date" date, "time" time, "member_first_name" varchar, "member_last_name" varchar, "member_email" varchar, "member_phone" varchar, "shooting_type" varchar, "additional_details" varchar, "created_at" datetime, "updated_at" datetime, foreign key("member_id") references "members"("id") on delete set null, foreign key("category_id") references "categories"("id") on delete set null, foreign key("sub_category_id") references "categories"("id") on delete set null);
CREATE UNIQUE INDEX "bookings_booking_id_unique" on "bookings" ("booking_id");
CREATE TABLE IF NOT EXISTS "freelances" ("id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "speciality" varchar not null, "experience" varchar not null, "phone" varchar not null, "portfolio" varchar, "status" varchar not null default 'Pending', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
CREATE TABLE IF NOT EXISTS "freelancers" ("id" integer primary key autoincrement not null, "first_name" varchar not null, "last_name" varchar not null, "speciality" varchar not null, "experience" varchar not null, "phone" varchar not null, "portfolio" varchar, "status" varchar not null default 'Pending', "created_at" datetime, "updated_at" datetime, "deleted_at" datetime);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_05_11_000000_create_otps_table',1);
INSERT INTO migrations VALUES(5,'2024_03_28_162144_create_media_table',1);
INSERT INTO migrations VALUES(6,'2024_03_28_162642_create_categories_table',1);
INSERT INTO migrations VALUES(7,'2024_03_28_174828_create_members_table',1);
INSERT INTO migrations VALUES(8,'2024_03_28_175002_create_pages_table',1);
INSERT INTO migrations VALUES(9,'2024_03_28_175043_create_FAQs_table',1);
INSERT INTO migrations VALUES(10,'2024_03_28_175101_create_contact_us_table',1);
INSERT INTO migrations VALUES(11,'2024_03_29_110729_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(12,'2024_03_29_180400_create_bookings_table',1);
INSERT INTO migrations VALUES(13,'2024_04_02_200627_create_freelances_table',2);
INSERT INTO migrations VALUES(14,'2024_04_02_200627_create_freelancers_table',3);
